In [14]:
#Ler planilha de dados
import pandas as pd

In [15]:
import numpy as np

In [16]:
import pickle

In [17]:
import tensorflow as tf
loaded_model = tf.keras.models.load_model('dnn_pickle_all_apps_all_metrics.h5')

In [19]:
# dataset = pd.read_excel('metricas_jhawk_pmd_safe_linux_v1_sem_classe_bug.xlsx')
# dataset = pd.read_excel('metricas_jhawk_pmd_notepad_linux_v1_sem_classe_bug.xlsx')
# dataset = pd.read_excel('metricas_jhawk_pmd_avare_linux_v1_sem_classe_bug.xlsx')
# dataset = pd.read_excel('metricas_jhawk_pmd_AnyMemo_linux_v1_sem_classe_bug.xlsx')
dataset = pd.read_excel('metricas_jhawk_pmd_seadroid_linux_v1_sem_classe_bug.xlsx')

In [20]:
dataset = dataset[['closeByAnotherComponent','calledCloseComponent',
           'onPause','onStop','onDestroy',
            'CloseResource']]

In [21]:
dataset

closeByAnotherComponent  calledCloseComponent  onPause  onStop  \
0                          0                     0        0       0   
1                          0                     0        0       0   
2                          0                     0        0       0   
3                          0                     0        0       0   
4                          0                     0        0       0   
5                          0                     0        0       0   
6                          0                     0        0       0   
7                          0                     0        0       0   
8                          0                     0        0       0   
9                          0                     0        0       0   
10                         0                     0        0       0   
11                         0                     1        0       0   
12                         0                     0        0       0   
13                         0                     0        0       0   
14                         0                     0        0       0   
15                         0                     0        0       0   
16                         0                     0        0       0   
17                         0                     0        0       0   
18                         0                     0        0       0   
19                         0                     0        0       0   
20                         0                     0        0       0   
21                         0                     0        0       0   
22                         0                     0        0       0   
23                         0                     0        0       0   
24                         0                     0        0       0   
25                         0                     0        0       0   
26                         0                     0        0       0   
27                         0                     0        0       0   
28                         0                     0        0       0   
29                         0                     0        0       0   
..                       ...                   ...      ...     ...   
327                        0                     0        0       0   
328                        0                     1        0       0   
329                        0                     0        0       0   
330                        0                     1        0       0   
331                        0                     1        0       0   
332                        0                     1        0       0   
333                        0                     1        0       0   
334                        1                     0        0       0   
335                        0                     0        0       0   
336                        0                     0        0       0   
337                        0                     0        0       0   
338                        0                     0        0       0   
339                        0                     1        0       0   
340                        0                     0        0       0   
341                        0                     0        0       0   
342                        1                     0        0       0   
343                        0                     0        0       0   
344                        0                     0        0       0   
345                        0                     0        0       0   
346                        0                     0        0       0   
347                        1                     0        0       0   
348                        0                     1        0       0   
349                        0                     0        0       0   
350                        0                     1        0       0   
351                        0 

In [22]:
dataset= dataset.replace(np.nan,0)

In [23]:
dataset

closeByAnotherComponent  calledCloseComponent  onPause  onStop  \
0                          0                     0        0       0   
1                          0                     0        0       0   
2                          0                     0        0       0   
3                          0                     0        0       0   
4                          0                     0        0       0   
5                          0                     0        0       0   
6                          0                     0        0       0   
7                          0                     0        0       0   
8                          0                     0        0       0   
9                          0                     0        0       0   
10                         0                     0        0       0   
11                         0                     1        0       0   
12                         0                     0        0       0   
13                         0                     0        0       0   
14                         0                     0        0       0   
15                         0                     0        0       0   
16                         0                     0        0       0   
17                         0                     0        0       0   
18                         0                     0        0       0   
19                         0                     0        0       0   
20                         0                     0        0       0   
21                         0                     0        0       0   
22                         0                     0        0       0   
23                         0                     0        0       0   
24                         0                     0        0       0   
25                         0                     0        0       0   
26                         0                     0        0       0   
27                         0                     0        0       0   
28                         0                     0        0       0   
29                         0                     0        0       0   
..                       ...                   ...      ...     ...   
327                        0                     0        0       0   
328                        0                     1        0       0   
329                        0                     0        0       0   
330                        0                     1        0       0   
331                        0                     1        0       0   
332                        0                     1        0       0   
333                        0                     1        0       0   
334                        1                     0        0       0   
335                        0                     0        0       0   
336                        0                     0        0       0   
337                        0                     0        0       0   
338                        0                     0        0       0   
339                        0                     1        0       0   
340                        0                     0        0       0   
341                        0                     0        0       0   
342                        1                     0        0       0   
343                        0                     0        0       0   
344                        0                     0        0       0   
345                        0                     0        0       0   
346                        0                     0        0       0   
347                        1                     0        0       0   
348                        0                     1        0       0   
349                        0                     0        0       0   
350                        0                     1        0       0   
351                        0 

In [24]:
result = loaded_model.predict(dataset)

In [25]:
result

array([[0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.54799104],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.54570395],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216547],
       [0.25216547],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.25216544],
       [0.252

In [26]:
result.round() #seadroid dnn_pickle_all_apps.h5

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [13]:
result.round() #AnyMemo dnn_pickle_all_apps.h5

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],

In [16]:
result.round() #avare dnn_pickle_all_apps.h5

array([[1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],

In [11]:
result.round() #notepad dnn_pickle_all_apps.h5

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [23]:
result.round() #safe dnn_pickle_all_apps.h5

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],